@startuml Retiros

skinparam linetype ortho
skinparam nodesep 60
skinparam ranksep 70

class Usuario {
  - nombre
  - apellido
  - email
  - telefono
  - retiro : Retiro
  - recordatorio : Recordatorio
  + crear()
  + mostrar()
  + conocerRetiro()
  + conocerRecordatorio()
  + calcularGastosTotales()
  + calcularGastosPorPeriodo()
}

class Retiro {
  - nombre
  - ubicacion
  - fechaInicio
  - fechaFin
  - duracion
  - costoTotal
  - requisitos
  - contactoOrganizador
  - estado : EstadoRetiro
  - actividad : Actividad
  - acompanante : Acompanante
  - pago : Pago
  - valoracion : Valoracion
  + crear()
  + mostrar()
  + conocerEstadoRetiro()
  + conocerActividad()
  + conocerAcompanante()
  + conocerPago()
  + conocerValoracion()
  + cambiarEstado()
  + agregarActividad()
  + agregarAcompanante()
  + registrarPago()
  + registrarValoracion()
  + calcularTotalGastos()
  + compartirInfo()
}
class EstadoRetiro {
  - valor
  + crear()
  + mostrar()
  + tomarValor()
  + mostrarValor()
}

class Actividad {
  - nombre
  - descripcion
  - fechaHora
  - costo
  + crear()
  + mostrar()
  + modificar()
}

class Acompanante {
  - nombre
  - apellido
  - telefono
  - vinculo : TipoVinculo
  + crear()
  + mostrar()
  + conocerTipoVinculo()
  + modificar()
}
@enduml